name: Docker Image 

on:
  push:
    branches:
      - task

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "login to docker hub"
        run: docker login --username ${{ secrets.USER_NAME }} --password ${{ secrets.TOKEN }}

      - name: "build image"
        run: docker build -t ${{ secrets.USER_NAME }}/ostasktwo

      - name: "push image to docker hub"
        run: docker push ${{ secrets.USER_NAME }}/ostasktwo