name: Docker Image CI

on:
  push:
    branches:
      - task

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: 'Build the Docker image'
      run: echo abdo   

    - name: 'listing the files'
      run: ls

    - uses: actions/checkout@v3

    - name: 'listing after adding files to branch'
      run: ls